### ISSUE TITLE
Flog#initialize fails to set default parser (`'Flog#flog_ruby!': undefined method 'new' for nil (NoMethodError)`)

### ISSUE THREAD

**Issue by marco-nicola** [seattlerb/flog#84]
Hi,

after upgrading from v4.9.1 to v4.9.2, running the `flog` command with no option fails with the following error:

```
/home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog.rb:216:in 'Flog#flog_ruby!': undefined method 'new' for nil (NoMethodError)

    @parser = option[:parser].new
                             ^^^^
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog.rb:190:in 'Flog#flog_ruby'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog.rb:178:in 'block in Flog#flog'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog.rb:173:in 'Array#each'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog.rb:173:in 'Flog#flog'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog_cli.rb:174:in 'FlogCLI#flog'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/lib/flog_cli.rb:35:in 'FlogCLI.run'
        from /home/m/.asdf/installs/ruby/3.4.4/lib/ruby/gems/3.4.0/gems/flog-4.9.2/bin/flog:5:in '<top (required)>'
        from /home/m/.asdf/installs/ruby/3.4.4/bin/flog:25:in 'Kernel#load'
        from /home/m/.asdf/installs/ruby/3.4.4/bin/flog:25:in '<main>'
```

I think this is due to the following commit: https://github.com/seattlerb/flog/commit/108e801fb523cf2df781c62916440deb8607359d

`Flog#initialize` has this `option` parameter. A _copy_ of its value is assigned to the instance variable `@option = option.dup`. After that, we have `option[:parser] ||= NotRubyParser`: this is assigning a default parser to the `option` parameter, without affecting the `attr_reader` backed by `@option`.

Before that commit, modifying the parameter was affecting the attribute (or instance variable) as well, but now, since the value is copied, the default parser assignment becomes ineffective. So, unless a parser was already present in the options passed to the constructor (e.g. specifying `--legacy`), no fallback default parser is set.

Later on, in `Flog#flog_ruby!`, the line `@parser = option[:parser].new` fails, because `option[:parser]` is still `nil`.

**Comment by zenspider** [comment]
This should be addressed and released now. Thanks!
